Repository jetstack/dependency-track-exporter, pull requests merged in 2023-02, with the labels that each got.

#45 Add .gitignore
  .gitignore
Labels: size/L

#46 Fix required permission to run the exporter
  README.md
Labels: size/XS

#47 Enhance Dockerfile adding multistage build
  .goreleaser.yaml
  Dockerfile
  Dockerfile.goreleaser
Labels: size/M

#51 Bump client-go to pick up pagination fix
  go.mod
  go.sum
  internal/exporter/exporter.go
  internal/exporter/exporter_test.go
Labels: size/L
